---
title: "HSE711_Final_Project"
author: "Greg Fisher"
date: "2026-09-29"
output: pdf_document
---


```{r, setup, include=FALSE, message=FALSE}

library(tidyverse)

```

```{r echo=FALSE}

# Read in both data sets
count.df <- read.csv(file = "data/counts.csv", header = TRUE)
meta_data.df <- read.csv(file = "data/meta_data.csv", header = TRUE)
```

```{r, message=FALSE}

metadata.modified <- meta_data.df %>%
  dplyr::select(1,10,23,29,41) %>%
  mutate(barcode = str_replace_all(barcode, "-", "."))

```

```{r, message=FALSE}

# Convert count.df to long format

dat.long <- count.df %>%
  pivot_longer(
    cols = -X,        # Pivot all columns except the new row_id column
    names_to = "Samples",    # Column name for your old wide headers
    values_to = "Counts"    # Column name for your data values
  )

```


```{r, message=FALSE}

dat.long.enriched <- dat.long %>%
  mutate(X = sub("\\.[^.]*$", "", X)) %>%
  inner_join(., metadata.modified, by = c("Samples" = "barcode"))

```

```{r, message=FALSE, warning=FALSE}
library(AnnotationDbi)
library(org.Hs.eg.db)

count.df.mod <- count.df %>%
  mutate(X = sub("\\.[^.]*$", "", X))

ensemble.ids <- count.df.mod %>% pull(X)


ensembl_ids <- ensemble.ids

# Map IDs to Gene Symbols
gene_symbols <- mapIds(
  x = org.Hs.eg.db,
  keys = ensembl_ids,
  keytype = "ENSEMBL",
  column = "SYMBOL",
  multiVals = "first" # Keeps the first match if duplicate mappings occur
)

df <- data.frame(names(gene_symbols),gene_symbols)


```
```{r, message=FALSE, warning=FALSE}


dat.long.genes <- dat.long.enriched %>%
#  mutate(X = sub("\\.[^.]*$", "", X)) %>%
  inner_join(., df, by = c("X" = "names.gene_symbols."))

```
\newpage

```{r, message=FALSE, warning=FALSE}
# 1. barplot
dat.long.genes %>%
  filter(gene_symbols == 'BRCA1') %>%
  ggplot(., aes(x=Counts, fill = ajcc_pathologic_stage)) +
  geom_histogram(alpha = 0.5, binwidth = 1000) +
  labs(
    title = "Distribution of BRACA1 Gene Counts",
    x = "AJCC Pathological Stage",
    y = "Count (Frequency)"
  )
  
```
\newpage

```{r, message=FALSE, warning=FALSE}

dat.long.genes %>%
  filter(gene_symbols == 'BRCA1') %>%
  ggplot(., aes(x=ajcc_pathologic_stage,y=Counts)) +
  geom_violin() +
  labs(
    title = "Distribution of BRACA1 Gene Counts",
    x = "AJCC Pathological Stage",
    y = "Count (Frequency)"
  ) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

```
\newpage
```{r, message=FALSE, warning=FALSE}

summary_stats <- dat.long.genes %>%
  filter(gene_symbols == 'BRCA2') %>%
  summarize(
    min = min(Counts, na.rm = TRUE),
    max = max(Counts, na.rm = TRUE),
    mean = mean(Counts, na.rm = TRUE),
    median = median(Counts, na.rm = TRUE),
    sd = sd(Counts, na.rm = TRUE)
  )
summary_stats

```
\newpage
```{r, message=FALSE, warning=FALSE}

genes.of.interest <- c('BRCA1', 'BRCA2')

#df_test <- dat.long.genes %>%
dat.long.genes %>%
#  filter(gene_symbols == 'BRCA1' | gene_symbols == 'MYCBP2') %>%
  filter(gene_symbols %in% genes.of.interest) %>%
  dplyr::select(-1) %>%
  pivot_wider(names_from = gene_symbols, values_from = Counts) %>%
  ggplot(., aes(x=BRCA1,y=BRCA2)) +
  geom_point()

#df_test <- dat.long.genes %>%
#   filter(gene_symbols %in% genes.of.interest) %>%
#   dplyr::select(-1) %>%
#   pivot_wider(names_from = gene_symbols, values_from = Counts)

```